class UserAlreadyExistsError(Exception):
    ...

class DatabaseError(Exception):
    ...

class NoAvailiableUserError(Exception):
    ...

class BaseAlreadyExists(Exception):
    ...

class DomainAlreadyExists(BaseAlreadyExists):
    ...

class EnvAlreadyExists(BaseAlreadyExists):
    ...

class ProjectAlreadyExists(BaseAlreadyExists):
    ...

class BaseNotFound(Exception):
    ...

class DomainNotFound(BaseNotFound):
    ...

class EnvNotFound(BaseNotFound):
    ...

class ProjectNotFound(BaseNotFound):
    ...
