"""add default value for field locktime at User model

Revision ID: 40d8dda7da19
Revises: 84087efec833
Create Date: 2026-03-27 19:26:03.334923

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '40d8dda7da19'
down_revision: Union[str, Sequence[str], None] = '84087efec833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
