"""prohibit env, domain, project be null in User model

Revision ID: 84087efec833
Revises: 4d9a593efe55
Create Date: 2026-03-27 02:14:51.342968

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '84087efec833'
down_revision: str | Sequence[str] | None = '4d9a593efe55'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
