"""add autogenerate uuid4 fields to project, domain, env

Revision ID: 8a39920fea7c
Revises: 40d8dda7da19
Create Date: 2026-03-28 00:35:07.625390

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8a39920fea7c'
down_revision: Union[str, Sequence[str], None] = '40d8dda7da19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_domain_id'), 'domain', ['id'], unique=False)
    op.create_index(op.f('ix_env_id'), 'env', ['id'], unique=False)
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_index(op.f('ix_env_id'), table_name='env')
    op.drop_index(op.f('ix_domain_id'), table_name='domain')
    # ### end Alembic commands ###
