"""add autogenerate server uuid4 fields to user, project, domain, env models

Revision ID: d35c4cb929c2
Revises: 8a39920fea7c
Create Date: 2026-03-28 00:57:35.351946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd35c4cb929c2'
down_revision: Union[str, Sequence[str], None] = '8a39920fea7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
